/**
 * Tier 1: Offline protocol unit tests (no hardware required)
 *
 * Tests the serial command byte sequences generated by DisplayDevice
 * and validates safety-critical code paths (buffer handling, string ops).
 *
 * Build:  cd build && cmake -DBUILD_TESTS=ON .. && make test_protocol
 * Run:    ./build/test_protocol
 */

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
#include <functional>
#include <map>
#include <iostream>
#include <sstream>

// Include project headers for constants
#include "Config.h"

// ============================================================================
// Minimal test framework (no external dependencies)
// ============================================================================

static int g_testsPassed = 0;
static int g_testsFailed = 0;
static std::string g_currentTest;

struct TestFailure {
    std::string test;
    std::string file;
    int line;
    std::string message;
};
static std::vector<TestFailure> g_failures;

#define TEST(name) \
    static void test_##name(); \
    static bool _reg_##name = registerTest(#name, test_##name); \
    static void test_##name()

#define ASSERT_TRUE(cond) \
    do { if (!(cond)) { \
        g_failures.push_back({g_currentTest, __FILE__, __LINE__, \
            "ASSERT_TRUE(" #cond ") failed"}); \
        g_testsFailed++; return; \
    }} while(0)

#define ASSERT_FALSE(cond) \
    do { if (cond) { \
        g_failures.push_back({g_currentTest, __FILE__, __LINE__, \
            "ASSERT_FALSE(" #cond ") failed"}); \
        g_testsFailed++; return; \
    }} while(0)

#define ASSERT_EQ(a, b) \
    do { if ((a) != (b)) { \
        std::ostringstream _oss; \
        _oss << "ASSERT_EQ(" #a ", " #b ") failed: " << (a) << " != " << (b); \
        g_failures.push_back({g_currentTest, __FILE__, __LINE__, _oss.str()}); \
        g_testsFailed++; return; \
    }} while(0)

#define ASSERT_BYTES_EQ(actual, expected, len) \
    do { \
        bool _match = (memcmp((actual), (expected), (len)) == 0); \
        if (!_match) { \
            std::ostringstream _oss; \
            _oss << "ASSERT_BYTES_EQ failed at " #actual " vs " #expected \
                 << " (" << (len) << " bytes)\n  actual:   "; \
            for (size_t _i = 0; _i < (size_t)(len); _i++) \
                _oss << std::hex << "0x" << (int)((const uint8_t*)(actual))[_i] << " "; \
            _oss << "\n  expected: "; \
            for (size_t _i = 0; _i < (size_t)(len); _i++) \
                _oss << std::hex << "0x" << (int)((const uint8_t*)(expected))[_i] << " "; \
            g_failures.push_back({g_currentTest, __FILE__, __LINE__, _oss.str()}); \
            g_testsFailed++; return; \
        } \
    } while(0)

static std::vector<std::pair<std::string, std::function<void()>>> g_tests;

static bool registerTest(const char* name, std::function<void()> fn) {
    g_tests.push_back({name, fn});
    return true;
}

// ============================================================================
// Mock DisplayDevice - captures bytes instead of writing to serial
// ============================================================================

class MockDisplayDevice {
public:
    std::vector<uint8_t> lastCommand;
    std::vector<std::vector<uint8_t>> allCommands;

    void sendCommand(const uint8_t* data, size_t length) {
        lastCommand.assign(data, data + length);
        allCommands.push_back(lastCommand);
    }

    void clear() {
        uint8_t cmd = Config::CMD_CLEAR;
        sendCommand(&cmd, 1);
    }

    // Current protocol: [0x02][x][y][text...]
    void drawText_current(int x, int y, const std::string& text) {
        size_t textLen = text.length();
        std::vector<uint8_t> cmd(textLen + 3);
        cmd[0] = Config::CMD_DRAW_TEXT;
        cmd[1] = static_cast<uint8_t>(x);
        cmd[2] = static_cast<uint8_t>(y);
        memcpy(cmd.data() + 3, text.c_str(), textLen);
        sendCommand(cmd.data(), cmd.size());
    }

    // New protocol (H0a): [0x02][x][y][len][text...]
    void drawText_v2(int x, int y, const std::string& text) {
        size_t textLen = text.length();
        // Clamp to firmware max (128 - 4 byte header)
        constexpr size_t MAX_TEXT_LEN = 124;
        if (textLen > MAX_TEXT_LEN) {
            textLen = MAX_TEXT_LEN;
        }
        std::vector<uint8_t> cmd(textLen + 4);
        cmd[0] = Config::CMD_DRAW_TEXT;
        cmd[1] = static_cast<uint8_t>(x);
        cmd[2] = static_cast<uint8_t>(y);
        cmd[3] = static_cast<uint8_t>(textLen);
        memcpy(cmd.data() + 4, text.c_str(), textLen);
        sendCommand(cmd.data(), cmd.size());
    }

    void setCursor(int x, int y) {
        uint8_t cmd[3];
        cmd[0] = Config::CMD_SET_CURSOR;
        cmd[1] = static_cast<uint8_t>(x);
        cmd[2] = static_cast<uint8_t>(y);
        sendCommand(cmd, 3);
    }

    void setInverted(bool inverted) {
        uint8_t cmd[2];
        cmd[0] = Config::CMD_INVERT;
        cmd[1] = inverted ? 1 : 0;
        sendCommand(cmd, 2);
    }

    void setBrightness(int brightness) {
        uint8_t cmd[2];
        cmd[0] = Config::CMD_BRIGHTNESS;
        cmd[1] = static_cast<uint8_t>(brightness);
        sendCommand(cmd, 2);
    }

    void drawProgressBar(int x, int y, int width, int height, int percentage) {
        uint8_t cmd[6];
        cmd[0] = Config::CMD_PROGRESS_BAR;
        cmd[1] = static_cast<uint8_t>(x);
        cmd[2] = static_cast<uint8_t>(y);
        cmd[3] = static_cast<uint8_t>(width);
        cmd[4] = static_cast<uint8_t>(height);
        cmd[5] = static_cast<uint8_t>(percentage);
        sendCommand(cmd, 6);
    }

    void setPower(bool on) {
        uint8_t cmd[2];
        cmd[0] = Config::CMD_POWER_MODE;
        cmd[1] = on ? 0x01 : 0x00;
        sendCommand(cmd, 2);
    }

    void reset() {
        lastCommand.clear();
        allCommands.clear();
    }
};

// ============================================================================
// Protocol byte-sequence tests (current protocol)
// ============================================================================

TEST(clear_command_byte) {
    MockDisplayDevice dev;
    dev.clear();
    ASSERT_EQ(dev.lastCommand.size(), (size_t)1);
    ASSERT_EQ(dev.lastCommand[0], Config::CMD_CLEAR);
}

TEST(drawText_current_hello_at_origin) {
    MockDisplayDevice dev;
    dev.drawText_current(0, 0, "Hello");
    // Expected: [0x02, 0x00, 0x00, 'H', 'e', 'l', 'l', 'o']
    ASSERT_EQ(dev.lastCommand.size(), (size_t)8);
    ASSERT_EQ(dev.lastCommand[0], Config::CMD_DRAW_TEXT);
    ASSERT_EQ(dev.lastCommand[1], 0x00);  // x
    ASSERT_EQ(dev.lastCommand[2], 0x00);  // y
    ASSERT_EQ(dev.lastCommand[3], 'H');
    ASSERT_EQ(dev.lastCommand[7], 'o');
}

TEST(drawText_current_at_position) {
    MockDisplayDevice dev;
    dev.drawText_current(10, 16, "AB");
    // Expected: [0x02, 0x0A, 0x10, 'A', 'B']
    ASSERT_EQ(dev.lastCommand.size(), (size_t)5);
    ASSERT_EQ(dev.lastCommand[0], Config::CMD_DRAW_TEXT);
    ASSERT_EQ(dev.lastCommand[1], 0x0A);  // x=10
    ASSERT_EQ(dev.lastCommand[2], 0x10);  // y=16
    ASSERT_EQ(dev.lastCommand[3], 'A');
    ASSERT_EQ(dev.lastCommand[4], 'B');
}

TEST(drawText_current_empty_string) {
    MockDisplayDevice dev;
    dev.drawText_current(0, 0, "");
    // Expected: [0x02, 0x00, 0x00] (header only, no text)
    ASSERT_EQ(dev.lastCommand.size(), (size_t)3);
    ASSERT_EQ(dev.lastCommand[0], Config::CMD_DRAW_TEXT);
}

TEST(setCursor_command) {
    MockDisplayDevice dev;
    dev.setCursor(64, 32);
    ASSERT_EQ(dev.lastCommand.size(), (size_t)3);
    ASSERT_EQ(dev.lastCommand[0], Config::CMD_SET_CURSOR);
    ASSERT_EQ(dev.lastCommand[1], 64);
    ASSERT_EQ(dev.lastCommand[2], 32);
}

TEST(invert_on_off) {
    MockDisplayDevice dev;
    dev.setInverted(true);
    ASSERT_EQ(dev.lastCommand.size(), (size_t)2);
    ASSERT_EQ(dev.lastCommand[0], Config::CMD_INVERT);
    ASSERT_EQ(dev.lastCommand[1], 1);

    dev.setInverted(false);
    ASSERT_EQ(dev.lastCommand[1], 0);
}

TEST(brightness_min_max) {
    MockDisplayDevice dev;
    dev.setBrightness(0);
    ASSERT_EQ(dev.lastCommand.size(), (size_t)2);
    ASSERT_EQ(dev.lastCommand[0], Config::CMD_BRIGHTNESS);
    ASSERT_EQ(dev.lastCommand[1], 0);

    dev.setBrightness(255);
    ASSERT_EQ(dev.lastCommand[1], 255);
}

TEST(progress_bar_command) {
    MockDisplayDevice dev;
    dev.drawProgressBar(10, 30, 108, 12, 75);
    ASSERT_EQ(dev.lastCommand.size(), (size_t)6);
    ASSERT_EQ(dev.lastCommand[0], Config::CMD_PROGRESS_BAR);
    ASSERT_EQ(dev.lastCommand[1], 10);   // x
    ASSERT_EQ(dev.lastCommand[2], 30);   // y
    ASSERT_EQ(dev.lastCommand[3], 108);  // width
    ASSERT_EQ(dev.lastCommand[4], 12);   // height
    ASSERT_EQ(dev.lastCommand[5], 75);   // percentage
}

TEST(power_on_off) {
    MockDisplayDevice dev;
    dev.setPower(true);
    ASSERT_EQ(dev.lastCommand.size(), (size_t)2);
    ASSERT_EQ(dev.lastCommand[0], Config::CMD_POWER_MODE);
    ASSERT_EQ(dev.lastCommand[1], 0x01);

    dev.setPower(false);
    ASSERT_EQ(dev.lastCommand[1], 0x00);
}

// ============================================================================
// New protocol tests (H0a: CMD_DRAW_TEXT with length byte)
// ============================================================================

TEST(drawText_v2_hello_at_origin) {
    MockDisplayDevice dev;
    dev.drawText_v2(0, 0, "Hello");
    // Expected: [0x02, 0x00, 0x00, 0x05, 'H', 'e', 'l', 'l', 'o']
    ASSERT_EQ(dev.lastCommand.size(), (size_t)9);
    ASSERT_EQ(dev.lastCommand[0], Config::CMD_DRAW_TEXT);
    ASSERT_EQ(dev.lastCommand[1], 0x00);  // x
    ASSERT_EQ(dev.lastCommand[2], 0x00);  // y
    ASSERT_EQ(dev.lastCommand[3], 0x05);  // len=5
    ASSERT_EQ(dev.lastCommand[4], 'H');
    ASSERT_EQ(dev.lastCommand[8], 'o');
}

TEST(drawText_v2_empty_string) {
    MockDisplayDevice dev;
    dev.drawText_v2(0, 0, "");
    // Expected: [0x02, 0x00, 0x00, 0x00] (header with len=0)
    ASSERT_EQ(dev.lastCommand.size(), (size_t)4);
    ASSERT_EQ(dev.lastCommand[3], 0x00);  // len=0
}

TEST(drawText_v2_max_length_clamp) {
    MockDisplayDevice dev;
    // Create a string longer than 124 bytes
    std::string longText(200, 'X');
    dev.drawText_v2(0, 0, longText);
    // Should clamp to 124 bytes of text + 4 byte header = 128 total
    ASSERT_EQ(dev.lastCommand.size(), (size_t)128);
    ASSERT_EQ(dev.lastCommand[3], (uint8_t)124);  // len clamped to 124
}

TEST(drawText_v2_exactly_124_bytes) {
    MockDisplayDevice dev;
    std::string text124(124, 'A');
    dev.drawText_v2(0, 0, text124);
    ASSERT_EQ(dev.lastCommand.size(), (size_t)128);
    ASSERT_EQ(dev.lastCommand[3], (uint8_t)124);
}

TEST(drawText_v2_at_cr_lf_coordinates) {
    // Verify coordinates that are CR (0x0D=13) or LF (0x0A=10)
    // are sent correctly as binary values (H0b verification)
    MockDisplayDevice dev;
    dev.drawText_v2(10, 13, "X");
    ASSERT_EQ(dev.lastCommand[1], 0x0A);  // x=10 = LF byte value
    ASSERT_EQ(dev.lastCommand[2], 0x0D);  // y=13 = CR byte value
    ASSERT_EQ(dev.lastCommand[3], 0x01);  // len=1
    ASSERT_EQ(dev.lastCommand[4], 'X');
}

// ============================================================================
// H0b: Verify no CR/LF terminators in any command
// ============================================================================

TEST(no_crlf_in_clear) {
    MockDisplayDevice dev;
    dev.clear();
    for (size_t i = 0; i < dev.lastCommand.size(); i++) {
        ASSERT_TRUE(dev.lastCommand[i] != '\r' || i > 0);  // Only check trailing bytes
    }
    // Clear is just [0x01] - one byte, no CR/LF appended
    ASSERT_EQ(dev.lastCommand.size(), (size_t)1);
}

TEST(no_crlf_appended_to_commands) {
    MockDisplayDevice dev;

    // Exercise all command types
    dev.clear();
    dev.drawText_v2(0, 0, "test");
    dev.setCursor(0, 0);
    dev.setInverted(true);
    dev.setBrightness(128);
    dev.drawProgressBar(0, 0, 100, 10, 50);
    dev.setPower(true);

    // Check that no command ends with CR or LF
    for (size_t c = 0; c < dev.allCommands.size(); c++) {
        const auto& cmd = dev.allCommands[c];
        ASSERT_TRUE(!cmd.empty());
        uint8_t lastByte = cmd.back();
        // Last byte should NOT be CR or LF (unless it's legitimate text content)
        // For non-text commands, last byte must not be 0x0A or 0x0D
        if (cmd[0] != Config::CMD_DRAW_TEXT) {
            ASSERT_TRUE(lastByte != 0x0A);
            ASSERT_TRUE(lastByte != 0x0D);
        }
    }
}

// ============================================================================
// C3: substr() safety tests for ModuleDependency pattern
// ============================================================================

// Replicate the vulnerable pattern from ModuleDependency.cpp:121
static bool isUrlPath_unsafe(const std::string& path) {
    // Original vulnerable code
    return (path.substr(0, 7) == "http://" || path.substr(0, 8) == "https://");
}

static bool isUrlPath_safe(const std::string& path) {
    // Fixed version using compare()
    return (path.length() >= 7 && path.compare(0, 7, "http://") == 0) ||
           (path.length() >= 8 && path.compare(0, 8, "https://") == 0);
}

TEST(url_check_safe_with_valid_urls) {
    ASSERT_TRUE(isUrlPath_safe("http://example.com"));
    ASSERT_TRUE(isUrlPath_safe("https://example.com"));
    ASSERT_TRUE(isUrlPath_safe("http://x"));
    ASSERT_TRUE(isUrlPath_safe("https://x"));
}

TEST(url_check_safe_with_file_paths) {
    ASSERT_FALSE(isUrlPath_safe("/usr/bin/script.sh"));
    ASSERT_FALSE(isUrlPath_safe("./relative/path"));
    ASSERT_FALSE(isUrlPath_safe("/etc/micropanel/config.json"));
}

TEST(url_check_safe_with_short_strings) {
    // These would throw std::out_of_range with the unsafe version
    ASSERT_FALSE(isUrlPath_safe(""));
    ASSERT_FALSE(isUrlPath_safe("h"));
    ASSERT_FALSE(isUrlPath_safe("http"));
    ASSERT_FALSE(isUrlPath_safe("http:/"));
    ASSERT_FALSE(isUrlPath_safe("https:"));
    ASSERT_FALSE(isUrlPath_safe("https:/"));
}

TEST(url_check_unsafe_crashes_on_short_strings) {
    // Verify the unsafe version does NOT crash on strings >= 8 chars
    ASSERT_TRUE(isUrlPath_unsafe("http://x"));
    ASSERT_TRUE(isUrlPath_unsafe("https://x"));
    ASSERT_FALSE(isUrlPath_unsafe("/usr/bin/x"));

    // Note: isUrlPath_unsafe("") would throw std::out_of_range
    // We don't call it here to avoid crashing the test runner,
    // but this documents the bug that C3 fixes.
}

// ============================================================================
// C2: strncpy safety pattern validation
// ============================================================================

TEST(strncpy_pattern_normal_name) {
    char dest[16];  // IFNAMSIZ
    const char* src = "eth0";
    strncpy(dest, src, sizeof(dest) - 1);
    dest[sizeof(dest) - 1] = '\0';
    ASSERT_EQ(strcmp(dest, "eth0"), 0);
}

TEST(strncpy_pattern_max_length) {
    char dest[16];
    const char* src = "123456789012345";  // exactly 15 chars
    strncpy(dest, src, sizeof(dest) - 1);
    dest[sizeof(dest) - 1] = '\0';
    ASSERT_EQ(strlen(dest), (size_t)15);
}

TEST(strncpy_pattern_overflow_prevented) {
    char dest[16];
    const char* src = "this_is_way_too_long_for_ifname";  // 30 chars
    strncpy(dest, src, sizeof(dest) - 1);
    dest[sizeof(dest) - 1] = '\0';
    ASSERT_EQ(strlen(dest), (size_t)15);  // Truncated, not overflowed
}

// ============================================================================
// Config.h constant validation
// ============================================================================

TEST(config_command_codes_are_unique) {
    std::vector<uint8_t> codes = {
        Config::CMD_CLEAR,
        Config::CMD_DRAW_TEXT,
        Config::CMD_SET_CURSOR,
        Config::CMD_INVERT,
        Config::CMD_BRIGHTNESS,
        Config::CMD_PROGRESS_BAR,
        Config::CMD_POWER_MODE,
    };
    // Check no duplicates
    for (size_t i = 0; i < codes.size(); i++) {
        for (size_t j = i + 1; j < codes.size(); j++) {
            ASSERT_TRUE(codes[i] != codes[j]);
        }
    }
}

TEST(config_command_codes_sequential) {
    ASSERT_EQ(Config::CMD_CLEAR, (uint8_t)0x01);
    ASSERT_EQ(Config::CMD_DRAW_TEXT, (uint8_t)0x02);
    ASSERT_EQ(Config::CMD_SET_CURSOR, (uint8_t)0x03);
    ASSERT_EQ(Config::CMD_INVERT, (uint8_t)0x04);
    ASSERT_EQ(Config::CMD_BRIGHTNESS, (uint8_t)0x05);
    ASSERT_EQ(Config::CMD_PROGRESS_BAR, (uint8_t)0x06);
    ASSERT_EQ(Config::CMD_POWER_MODE, (uint8_t)0x07);
}

TEST(cmd_buffer_size_sufficient) {
    // Buffer must be large enough for max command (drawText with 124 bytes + 4 header)
    ASSERT_TRUE(Config::CMD_BUFFER_SIZE >= 128);
}

// ============================================================================
// Display dimension sanity checks
// ============================================================================

TEST(display_text_padding_fits) {
    // 16-char padding convention must fit within display width
    // 128px / 6px per char = 21 chars max
    int maxChars = Config::DISPLAY_WIDTH / Config::CHAR_WIDTH;
    ASSERT_TRUE(maxChars >= 16);
}

TEST(menu_visible_items_fit) {
    // Menu items must fit below header (16px) in 64px display
    // Available: 64 - 16 = 48px, each item = 8px
    int availableHeight = Config::DISPLAY_HEIGHT - Config::MENU_START_Y;
    int maxItems = availableHeight / Config::MENU_ITEM_SPACING;
    ASSERT_TRUE(maxItems >= Config::MENU_VISIBLE_ITEMS);
}

// ============================================================================
// Main
// ============================================================================

int main(int argc, char* argv[]) {
    (void)argc; (void)argv;

    printf("Running %zu protocol unit tests...\n\n", g_tests.size());

    for (const auto& test : g_tests) {
        g_currentTest = test.first;
        int failsBefore = g_testsFailed;
        test.second();
        if (g_testsFailed == failsBefore) {
            g_testsPassed++;
            printf("  PASS  %s\n", test.first.c_str());
        } else {
            printf("  FAIL  %s\n", test.first.c_str());
        }
    }

    printf("\n");
    if (!g_failures.empty()) {
        printf("Failures:\n");
        for (const auto& f : g_failures) {
            printf("  %s:%d [%s] %s\n", f.file.c_str(), f.line,
                   f.test.c_str(), f.message.c_str());
        }
        printf("\n");
    }

    printf("Results: %d passed, %d failed, %d total\n",
           g_testsPassed, g_testsFailed, g_testsPassed + g_testsFailed);

    return g_testsFailed > 0 ? 1 : 0;
}
